CRITICAL - 2022-05-07 23:48:24 --> Invalid file: Myth\Auth\Views\_message_block.php
#0 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Myth\\Auth\\Views...')
#1 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#2 C:\xampp\htdocs\ci4rpl\app\Views\auth\login.php(14): view('Myth\\Auth\\Views...')
#3 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Common.php(1089): CodeIgniter\View\View->render('auth/login', Array, true)
#6 C:\xampp\htdocs\ci4rpl\app\Controllers\Home.php(9): view('auth/login')
#7 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Home->index()
#8 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4rpl\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ci4rpl\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
